# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2025 Erlang Ecosystem Foundation

on:
  workflow_call:
    inputs:
      releaseName:
        required: false
        type: string
    secrets:
      HEX_API_KEY:
        required: false

name: "Publish"

permissions:
  contents: read

jobs:
  hex_publish:
    name: rebar3 hex publish

    runs-on: ubuntu-latest

    environment: "release"

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-runtime-env

      - run: rebar3 hex publish -r hexpm --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
